# Generated by Django 5.2.8 on 2025-11-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tprm_rfp", "0016_add_org_field"),
        ("tprm_rfp", "0022_create_award_notification_model"),
    ]

    operations = []
