"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
import warnings
from dotenv import load_dotenv

# Load environment variables from .env file
# NOTE: override=True ensures that values from the local .env file
# take precedence over any existing OS-level environment variables.
# This avoids confusing situations where DB_USER/DB_PASSWORD are
# different in the system env vs the .env you are editing.
load_dotenv(override=True)

# =========================================================================
# SUPPRESS WARNINGS - Clean up terminal output
# =========================================================================
# Suppress Google API Python version warning
warnings.filterwarnings("ignore", category=FutureWarning, module="google.api_core")
# Suppress model registration warnings (we're using database router)
warnings.filterwarnings("ignore", category=RuntimeWarning, message=".*already registered.*")
# Suppress ALL development server warnings
warnings.filterwarnings("ignore", module="django.core.management.commands.runserver")
warnings.filterwarnings("ignore", message=".*development server.*")
warnings.filterwarnings("ignore", message=".*production.*")
import logging
logging.getLogger('django.utils.autoreload').setLevel(logging.ERROR)
logging.getLogger('django.server').setLevel(logging.ERROR)  # Suppress server startup messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add ai_services to Python path
sys.path.append(str(BASE_DIR.parent))

"""
SECURITY NOTE:
- DO NOT hardcode any secrets, API keys, passwords, or tokens in this file.
- All sensitive values must come from environment variables (or a .env file that is NOT committed).
"""

# External service keys (load from environment / .env)
PERPLEXITY_API_KEY = os.environ.get("PERPLEXITY_API_KEY", "")
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Must be provided via environment variable in production.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY is required. Set it in the environment or .env (never commit the value)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "false").lower() == "true"


def _env_bool(name: str, default: bool) -> bool:
    """Parse boolean from environment; used for cookie and HTTPS flags."""
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ("true", "1", "yes", "on")


# When False (production), cookies should use Secure + HSTS unless explicitly overridden.
_default_secure_cookies = not DEBUG

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'grc-riskavaire.vardaands.com',  # Main production domain
    'grc-tprm.vardaands.com',
    'grc-backend.vardaands.com',
    '15.207.108.158',
    '13.204.228.21',
    'e581-2405-201-c00b-4973-29e6-34b2-9eae-1e0c.ngrok-free.app',
]

# -----------------------------------------------------------------------------
# Trusted evidence / iframe URLs (security-critical)
# -----------------------------------------------------------------------------
# These lists are used to validate any URL fields that may be rendered by the UI
# (e.g., evidence links / iframe sources). Keep them strict and environment-driven.
def _env_csv(name: str, default: str = "") -> list[str]:
    v = os.environ.get(name, default)
    if not v:
        return []
    return [x.strip() for x in v.split(",") if x.strip()]

# Explicit hosts allowed for evidence URLs.
TRUSTED_EVIDENCE_URL_HOSTS = _env_csv(
    "TRUSTED_EVIDENCE_URL_HOSTS",
    # Default to your own app domains; extend via env for S3/CloudFront/custom storage.
    "grc-riskavaire.vardaands.com,grc-tprm.vardaands.com",
)

# Host suffixes allowed for evidence URLs (covers bucket.s3.<region>.amazonaws.com etc).
TRUSTED_EVIDENCE_URL_HOST_SUFFIXES = _env_csv(
    "TRUSTED_EVIDENCE_URL_HOST_SUFFIXES",
    "amazonaws.com,cloudfront.net",
)

# Allow http only for explicitly listed hosts (e.g., local dev or internal non-TLS services).
TRUSTED_EVIDENCE_URL_ALLOW_HTTP_HOSTS = _env_csv(
    "TRUSTED_EVIDENCE_URL_ALLOW_HTTP_HOSTS",
    "localhost,127.0.0.1",
)

# Export URL allowlist used by export SSRF hardening.
# Keep this strict in production. Empty means "allow public http/https only",
# while internal/private/link-local/loopback hosts remain blocked.
EXPORT_ALLOWED_DOMAINS = _env_csv("EXPORT_ALLOWED_DOMAINS", "")

# RiskAvaire EventHandling: HMAC-SHA256 of raw request body, header X-Riskavaire-Signature: sha256=<hex>
# When DEBUG is False, this must be non-empty or webhooks return 503 (misconfiguration).
RISKAVAIRE_WEBHOOK_SECRET = os.environ.get("RISKAVAIRE_WEBHOOK_SECRET", "").strip()

# EventHandling: allow outside DEBUG (off by default): schema DDL endpoints and
# test_integration_db_connection (creates integration DB / tables — use only for maintenance).
ALLOW_EVENT_SCHEMA_MAINTENANCE = os.environ.get(
    "ALLOW_EVENT_SCHEMA_MAINTENANCE", ""
).strip().lower() in ("1", "true", "yes")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "grc",
    
    # =========================================================================
    # TPRM INTEGRATION - Third Party Risk Management Apps
    # =========================================================================
    # Third-party dependencies for TPRM
    "django_filters",
    "drf_yasg",
    "import_export",
    "simple_history",
    
    # TPRM Core Apps
    "tprm_backend.core",
    "tprm_backend.slas",
    "tprm_backend.audits",
    "tprm_backend.notifications",
    "tprm_backend.quick_access",
    "tprm_backend.compliance",
    "tprm_backend.bcpdrp",
    "tprm_backend.risk_analysis",
    "tprm_backend.contract_risk_analysis",
    "tprm_backend.mfa_auth",
    "tprm_backend.rbac",
    "tprm_backend.admin_access",
    "tprm_backend.consent",
    "tprm_backend.contracts",
    "tprm_backend.audits_contract",
    "tprm_backend.rfp",
    "tprm_backend.rfp_approval",
    "tprm_backend.rfp_risk_analysis",
    "tprm_backend.ocr_app",
    "tprm_backend.global_search",
    "tprm_backend.risk_analysis_vendor",
    
    # TPRM Vendor Apps
    "tprm_backend.apps.vendor_core",
    "tprm_backend.apps.vendor_auth",
    "tprm_backend.apps.vendor_risk",
    "tprm_backend.apps.vendor_questionnaire",
    "tprm_backend.apps.vendor_dashboard",
    "tprm_backend.apps.vendor_lifecycle",
    "tprm_backend.apps.vendor_approval",
    "tprm_backend.apps.management",
]

MIDDLEWARE = [
    "grc.middleware.RequestLoggingMiddleware",  # ADDED: Log all requests FIRST
    "grc.middleware.ApiAbuseDetectionMiddleware",  # Real-time abuse detection and alerting
    "corsheaders.middleware.CorsMiddleware",
    # "grc.middleware.CORSMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "grc.db_connection_cleanup.DatabaseConnectionCleanupMiddleware",
 
    "django.contrib.sessions.middleware.SessionMiddleware",
    "grc.middleware.SessionTimeoutMiddleware",  # Session timeout middleware (configurable via SESSION_TIMEOUT_ENABLED env var)
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Framework-level safeguard: sanitize verbose JSON error payloads.
    "tprm_backend.middleware.error_sanitization.ErrorResponseSanitizationMiddleware",
    # Enterprise Security Headers Middleware - Adds comprehensive security headers to all responses
    "grc.middleware.EnterpriseSecurityHeadersMiddleware",
    # Validate server-side redirects to prevent open redirect vulnerabilities
    "grc.middleware.OutgoingRedirectValidationMiddleware",
    # Enforce request nonce + HMAC signature verification (replay/tamper protection)
    "grc.middleware.RequestSignatureVerificationMiddleware",
    "grc.middleware.JWTAuthenticationMiddleware",
    # Framework-level IDOR / object-level authorization (self-only unless admin)
    "grc.middleware.ObjectLevelAuthorizationMiddleware",
    # MULTI-TENANCY: Add tenant context middleware (after JWT authentication)
    "grc.tenant_middleware.TenantContextMiddleware",
    "grc.tenant_middleware.TenantIsolationMiddleware",
    # MULTI-TENANCY: Add TPRM tenant context middleware for TPRM modules
    "tprm_backend.core.tenant_middleware.TenantContextMiddleware",
    "tprm_backend.core.tenant_middleware.TenantIsolationMiddleware",
    "grc.middleware.AuditLoggingMiddleware",
    # AUTO-DECRYPT: Automatically decrypt any encrypted data in API responses (safety net)
    "grc.utils.auto_decrypt_middleware.AutoDecryptMiddleware",
    # Removed grc.rbac.middleware.GRCRBACMiddleware - using simplified decorator-based RBAC instead
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            BASE_DIR.parent / "frontend" / "dist",  # Vue.js production build
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Example SQLite config (commented out by default):
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# =============================================================================
# CACHE CONFIGURATION
# =============================================================================
# IMPORTANT: Use database-backed cache instead of LocMemCache.
# LocMemCache is wiped on every server restart, causing session tokens to be lost
# and producing 401 Unauthorized errors for all users after a restart.
# DatabaseCache persists tokens to MySQL and survives restarts.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",  # Table name in the default DB
    }
}

DATABASES = {
    "default": {
        # Use MySQL Connector/Python (same driver as in mysql_script.py)
        "ENGINE": "mysql.connector.django",
        "NAME": os.environ.get("DB_NAME", "grc2"),
        "USER": os.environ.get("DB_USER", "grc_user"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "MyP@ssw0rd!"),
        "HOST": os.environ.get("DB_HOST", "34.93.23.105"),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "auth_plugin": "caching_sha2_password",
            "connection_timeout": 10,
        },
    },

    # =========================================================================
    # TPRM Database - Third Party Risk Management
    # =========================================================================
    "tprm": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("TPRM_DB_NAME", "tprm_integration"),
        "USER": os.environ.get("TPRM_DB_USER", os.environ.get("DB_USER", "admin")),
        "PASSWORD": os.environ.get("TPRM_DB_PASSWORD", os.environ.get("DB_PASSWORD", "rootroot")),
        "HOST": os.environ.get("TPRM_DB_HOST", "tprmintegration.c1womgmu83di.ap-south-1.rds.amazonaws.com"),
        "PORT": os.environ.get("TPRM_DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
            "connect_timeout": 10,
        },
        "CONN_MAX_AGE": 60,  # Reuse connections for 60 seconds
        "CONN_HEALTH_CHECKS": True,  # Check connection health before use
    },
}

# =========================================================================
# DATABASE ROUTER - Route TPRM apps to TPRM database
# =========================================================================
DATABASE_ROUTERS = ['backend.tprm_router.TPRMDatabaseRouter']

# TPRM apps that should use the tprm database
TPRM_APPS = [
    'tprm_backend.core',
    'tprm_backend.slas',
    'tprm_backend.audits',
    'tprm_backend.notifications',
    'tprm_backend.quick_access',
    'tprm_backend.compliance',
    'tprm_backend.bcpdrp',
    'tprm_backend.risk_analysis',
    'tprm_backend.contract_risk_analysis',
    'tprm_backend.mfa_auth',
    'tprm_backend.rbac',
    'tprm_backend.admin_access',
    'tprm_backend.consent',  # TPRM Consent Management
    'tprm_backend.contracts',
    'tprm_backend.audits_contract',
    'tprm_backend.rfp',
    'tprm_backend.rfp_approval',
    'tprm_backend.rfp_risk_analysis',
    'tprm_backend.ocr_app',
    'tprm_backend.global_search',
    'tprm_backend.risk_analysis_vendor',
    'tprm_backend.apps.vendor_core',
    'tprm_backend.apps.vendor_auth',
    'tprm_backend.apps.vendor_risk',
    'tprm_backend.apps.vendor_questionnaire',
    'tprm_backend.apps.vendor_dashboard',
    'tprm_backend.apps.vendor_lifecycle',
    'tprm_backend.apps.vendor_approval',
]

# ===== SESSION CONFIGURATION - CRITICAL FOR AUTHENTICATION! =====
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database sessions
SESSION_SAVE_EVERY_REQUEST = False  # Don't extend session on every request - allows timeout to work properly

# Session Timeout Configuration (from environment variables)
# IMPORTANT: These values MUST be set in .env file - no hardcoded defaults
# SESSION_TIMEOUT_ENABLED: Enable/disable session timeout (required)
SESSION_TIMEOUT_ENABLED_STR = os.environ.get('SESSION_TIMEOUT_ENABLED')
if SESSION_TIMEOUT_ENABLED_STR is None:
    raise ValueError("❌ ERROR: SESSION_TIMEOUT_ENABLED must be set in .env file")
SESSION_TIMEOUT_ENABLED = SESSION_TIMEOUT_ENABLED_STR.lower() == 'true'

# SESSION_TIMEOUT_SECONDS: Session timeout duration in seconds (required)
SESSION_TIMEOUT_SECONDS_STR = os.environ.get('SESSION_TIMEOUT_SECONDS')
if SESSION_TIMEOUT_SECONDS_STR is None:
    raise ValueError("❌ ERROR: SESSION_TIMEOUT_SECONDS must be set in .env file")
SESSION_TIMEOUT_SECONDS = int(SESSION_TIMEOUT_SECONDS_STR)

# SESSION_COOKIE_AGE: Django session cookie age (should match or be longer than SESSION_TIMEOUT_SECONDS)
SESSION_COOKIE_AGE = SESSION_TIMEOUT_SECONDS

SESSION_COOKIE_NAME = 'grc_sessionid'  # Custom session cookie name
# Session ID must not be readable by JS (mitigates XSS session theft). Override via SESSION_COOKIE_HTTPONLY.
SESSION_COOKIE_HTTPONLY = _env_bool("SESSION_COOKIE_HTTPONLY", True)
# Send session cookie only over HTTPS in non-debug; override with SESSION_COOKIE_SECURE in .env.
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", _default_secure_cookies)
# Lax is the default so top-level OAuth returns (e.g. Google) still send the session cookie.
# Use SESSION_COOKIE_SAMESITE=Strict in .env only if you do not rely on cross-site login redirects.
SESSION_COOKIE_SAMESITE = os.environ.get("SESSION_COOKIE_SAMESITE", "Lax")
# High-security deployments: set SESSION_EXPIRE_AT_BROWSER_CLOSE=true to drop sessions when the browser closes.
SESSION_EXPIRE_AT_BROWSER_CLOSE = _env_bool("SESSION_EXPIRE_AT_BROWSER_CLOSE", False)
SESSION_COOKIE_DOMAIN = None  # Use default domain
SESSION_COOKIE_PATH = '/'  # Session cookie available for entire site


# CSRF cookie: Vue/axios reads csrftoken from document.cookie (see grc_frontend api.js xsrfCookieName).
# Keep CSRF_COOKIE_HTTPONLY=False unless you serve the token via meta/header/API only.
CSRF_COOKIE_HTTPONLY = _env_bool("CSRF_COOKIE_HTTPONLY", False)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", _default_secure_cookies)
CSRF_COOKIE_SAMESITE = os.environ.get("CSRF_COOKIE_SAMESITE", SESSION_COOKIE_SAMESITE)

# Add RBAC configuration for simplified decorator-based approach
RBAC_CONFIG = {
    'ENABLE_RBAC': False,  # Temporarily disable RBAC to fix 403 errors
    'LOG_PERMISSIONS': True,  # Log permission checks for debugging
    'DEBUG_MODE': True,  # Enable detailed debug logging during development
}

# RBAC Decorator Bypass for development
RBAC_DECORATOR_BYPASS = True  # Bypass RBAC decorators temporarily to fix 403 errors

# -----------------------------------------------------------------------------
# ENABLE_DEBUG_LOGGING: Control all verbose logging via environment variable
# Set ENABLE_DEBUG_LOGGING=true to enable DEBUG/INFO logs, false to disable (clean terminal)
# -----------------------------------------------------------------------------
ENABLE_DEBUG_LOGGING = os.environ.get("ENABLE_DEBUG_LOGGING", "false").lower() == "true"

# -----------------------------------------------------------------------------
# Security audit log: append-only file with SHA-256 hash chain (tamper detection).
# Production: also ship this file to WORM / S3 Object Lock / immutable storage.
# -----------------------------------------------------------------------------
SECURITY_AUDIT_LOG_ENABLED = _env_bool("SECURITY_AUDIT_LOG_ENABLED", True)
_logs_dir = BASE_DIR / "logs"
_logs_dir.mkdir(exist_ok=True)
SECURITY_AUDIT_LOG_PATH = str(
    Path(os.environ.get("SECURITY_AUDIT_LOG_PATH", _logs_dir / "security_audit_chain.log")).resolve()
)

LOGIN_ANOMALY_DETECTION_ENABLED = _env_bool("LOGIN_ANOMALY_DETECTION_ENABLED", True)
LOGIN_ANOMALY_MIN_BASELINE_LOGINS = int(os.environ.get("LOGIN_ANOMALY_MIN_BASELINE_LOGINS", "3"))
LOGIN_ANOMALY_HOUR_TOLERANCE = int(os.environ.get("LOGIN_ANOMALY_HOUR_TOLERANCE", "4"))
LOGIN_ANOMALY_REGION_WINDOW_SECONDS = int(os.environ.get("LOGIN_ANOMALY_REGION_WINDOW_SECONDS", "3600"))
LOGIN_ANOMALY_BASELINE_TTL = int(os.environ.get("LOGIN_ANOMALY_BASELINE_TTL", str(86400 * 90)))

# -----------------------------------------------------------------------------
# API Abuse Detection & Alerting
# -----------------------------------------------------------------------------
API_ABUSE_DETECTION_ENABLED = _env_bool("API_ABUSE_DETECTION_ENABLED", True)
API_ABUSE_RPS_THRESHOLD = int(os.environ.get("API_ABUSE_RPS_THRESHOLD", "300"))  # per-IP per minute
API_ABUSE_ERROR_THRESHOLD = int(os.environ.get("API_ABUSE_ERROR_THRESHOLD", "30"))  # per-IP per minute
API_ABUSE_WINDOW_SECONDS = int(os.environ.get("API_ABUSE_WINDOW_SECONDS", "60"))
API_ABUSE_EXEMPT_PATH_PREFIXES = _env_csv("API_ABUSE_EXEMPT_PATH_PREFIXES", "/admin/,/static/,/media/")

# Log level: DEBUG when enabled, ERROR when disabled (suppresses DEBUG/INFO/WARNING)
_DEBUG_LOG_LEVEL = "DEBUG" if ENABLE_DEBUG_LOGGING else "ERROR"
_CONSOLE_LEVEL = "DEBUG" if ENABLE_DEBUG_LOGGING else "ERROR"

# Add logging configuration for debugging
# IMPORTANT: Don't override django.server logger - it handles request logging automatically
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # CRITICAL: Keep Django's default loggers
    'filters': {
        'log_forging_safe': {
            '()': 'grc.utils.log_sanitize.LogForgingFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': _CONSOLE_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['log_forging_safe'],
        },
    },
    'loggers': {
        # DON'T override django.server or django.request - Django handles request logging automatically
        # Only suppress verbose autoreload messages
        'django.utils.autoreload': {
            'handlers': [],
            'level': 'ERROR',
            'propagate': False,
        },
        # GRC app logging - controlled by ENABLE_DEBUG_LOGGING
        'grc': {
            'handlers': ['console'],
            'level': _DEBUG_LOG_LEVEL,
            'propagate': True,
        },
        'grc.rbac': {
            'handlers': ['console'],
            'level': _DEBUG_LOG_LEVEL,
            'propagate': True,
        },
        # TPRM app logging - controlled by ENABLE_DEBUG_LOGGING
        'tprm_backend': {
            'handlers': ['console'],
            'level': _DEBUG_LOG_LEVEL,
            'propagate': True,
        },
    },
    # Root logger - catches everything else
    'root': {
        'handlers': ['console'],
        'level': _DEBUG_LOG_LEVEL,
    },
}

if SECURITY_AUDIT_LOG_ENABLED:
    LOGGING['handlers']['security_audit_chain'] = {
        'level': 'INFO',
        'class': 'grc.utils.integrity_log_handler.HashChainAppendOnlyFileHandler',
        'filename': SECURITY_AUDIT_LOG_PATH,
        'filters': ['log_forging_safe'],
    }
    LOGGING['loggers']['grc.security_audit'] = {
        'handlers': ['security_audit_chain'],
        'level': 'INFO',
        'propagate': False,
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'  # For collectstatic command

# Additional locations for static files (includes Vue.js dist)
# Only add directories that actually exist to avoid warnings
_potential_static_dirs = [
    BASE_DIR / "static_vendor_overrides",  # Overrides DRF/admin vendor JS (deprecated API mitigations)
    BASE_DIR.parent / 'frontend' / 'dist' / 'assets',  # Vue.js compiled assets
    BASE_DIR.parent / 'frontend' / 'dist' / 'css',     # Vue.js CSS
    BASE_DIR.parent / 'frontend' / 'dist' / 'js',      # Vue.js JS
]
STATICFILES_DIRS = [d for d in _potential_static_dirs if d.exists()]

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'MEDIA_ROOT'
# TEMP_MEDIA_ROOT can be configured via environment variable for deployment flexibility
# If not set, defaults to BASE_DIR / 'TEMP_MEDIA_ROOT'
TEMP_MEDIA_ROOT_ENV = os.environ.get('TEMP_MEDIA_ROOT', None)
if TEMP_MEDIA_ROOT_ENV:
    TEMP_MEDIA_ROOT = Path(TEMP_MEDIA_ROOT_ENV)
else:
    TEMP_MEDIA_ROOT = BASE_DIR / 'TEMP_MEDIA_ROOT'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================================
# SILENCED SYSTEM CHECKS - Suppress expected warnings
# =========================================================================
# Silence models.W035 warnings for tables shared across GRC and TPRM
# These are expected since we use DATABASE_ROUTERS to route to separate DBs
SILENCED_SYSTEM_CHECKS = [
    "models.W035",  # db_table used by multiple models (expected with multi-DB)
]

# CORS settings (security hardening)
# Never combine wildcard origin with credentials.
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

# Optional env-driven CORS extension:
# CORS_ALLOWED_ORIGINS_EXTRA="https://app.example.com,https://admin.example.com"
CORS_ALLOWED_ORIGINS = [
    "https://grc-tprm.vardaands.com",
    "https://test-riskavaire.vardaands.com",
    "http://localhost:3000",  # TPRM frontend development server
    "http://localhost:8081",  # Vue.js development server
    "http://localhost:8080",  # Alternative Vue.js port
    "http://127.0.0.1:3000",  # TPRM frontend development server (127.0.0.1)
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8081",
    "http://15.207.108.158:8080",  # AWS deployment frontend (HTTP)
    "http://15.207.108.158:8081",  # AWS deployment frontend alternative (HTTP)
    "https://15.207.108.158:8000",  # AWS backend HTTPS
    "https://15.207.108.158:8080",  # AWS frontend HTTPS
    "https://15.207.108.158:8081",  # AWS frontend alternative HTTPS
    "http://13.201.54.231",  # Deployed frontend URL
    "https://13.201.54.231",  # Deployed frontend URL (HTTPS)
    "http://13.201.54.231:80",  # Deployed frontend URL with port
    "http://13.201.54.231:8080",  # Deployed frontend URL with port
    "http://13.201.54.231:8081",  # Deployed frontend URL with port
    "https://grc-backend.vardaands.com",
    "https://13.204.228.21:8000",
    "http://13.204.228.21:8000",
    "https://grc-riskavaire.vardaands.com",
] + _env_csv("CORS_ALLOWED_ORIGINS_EXTRA")

# Support local dev ports without opening wildcard access.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(:\d+)?$",
    r"^http://127\.0\.0\.1(:\d+)?$",
]

# Allow localhost / 127.0.0.1 with any port when not using ALL_ORIGINS (e.g. production with DEBUG=False)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost(:\d+)?$",
    r"^http://127\.0\.0\.1(:\d+)?$",
]

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "https://grc-riskavaire.vardaands.com",
    "https://test-riskavaire.vardaands.com",
    "http://localhost:3000",  # TPRM frontend development server
    "http://localhost:8081",  # Vue.js development server
    "http://localhost:8080",  # Alternative Vue.js port
    "http://127.0.0.1:3000",  # TPRM frontend development server (127.0.0.1)
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8081",
    "http://15.207.108.158:8080",  # AWS deployment frontend (HTTP)
    "http://15.207.108.158:8081",  # AWS deployment frontend alternative (HTTP)
    "https://15.207.108.158:8000",  # AWS backend HTTPS
    "https://15.207.108.158:8080",  # AWS frontend HTTPS
    "https://15.207.108.158:8081",  # AWS frontend alternative HTTPS
    "http://13.201.54.231",  # Deployed frontend URL
    "https://13.201.54.231",  # Deployed frontend URL (HTTPS)
    "http://13.201.54.231:80",  # Deployed frontend URL with port
    "http://13.201.54.231:8080",  # Deployed frontend URL with port
    "http://13.201.54.231:8081",  # Deployed frontend URL with port
    "https://grc-backend.vardaands.com",  # New server IP with port
    "https://13.204.228.21:8000",  # New server IP with port (HTTPS)
    "http://13.204.228.21:8000",
    "https://grc-tprm.vardaands.com",
]

# Additional CORS settings
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cookie',  # CRITICAL: Allow cookie header for session authentication
    'set-cookie',  # Allow set-cookie header responses
]

# HTTPS / HSTS (session/CSRF cookie flags are set earlier; TLS often terminates at nginx)
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", str(31536000 if not DEBUG else 0)))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", not DEBUG)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", not DEBUG)
# CSRF_COOKIE_* and SESSION_COOKIE_* are defined earlier; do not override here (that forced
# CSRF_COOKIE_SECURE=False in production and undid env-based settings).

# Additional HTTPS security headers (enable in production)
# Nginx handles HTTP→HTTPS redirect, so Django redirect is off to avoid double-redirect.

# JWT Settings (Strictly asymmetric RS256; symmetric algorithms like HS256 are NOT allowed)
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM", "RS256").upper().strip()
JWT_ISSUER = os.environ.get("JWT_ISSUER", "grc-backend")
JWT_AUDIENCE = os.environ.get("JWT_AUDIENCE", "grc-frontend")

# Keys can be provided inline with \n in env vars.
JWT_PRIVATE_KEY = os.environ.get("JWT_PRIVATE_KEY", "").replace("\\n", "\n")
JWT_PUBLIC_KEY = os.environ.get("JWT_PUBLIC_KEY", "").replace("\\n", "\n")

_JWT_ASYMMETRIC_ALGS = ("RS256", "RS384", "RS512", "ES256", "ES384", "ES512")
if JWT_ALGORITHM not in _JWT_ASYMMETRIC_ALGS:
    raise ValueError(
        f"Insecure JWT_ALGORITHM ({JWT_ALGORITHM}) detected. "
        "The system strictly requires asymmetric signing (e.g., RS256 or ES256). "
        "Set JWT_ALGORITHM=RS256 and configure JWT_PRIVATE_KEY / JWT_PUBLIC_KEY."
    )

if not JWT_PRIVATE_KEY or not JWT_PUBLIC_KEY:
    raise ValueError(
        "JWT_PRIVATE_KEY and JWT_PUBLIC_KEY must be configured when using asymmetric JWT algorithms."
    )

JWT_SIGNING_KEY = JWT_PRIVATE_KEY
JWT_VERIFYING_KEY = JWT_PUBLIC_KEY

# Legacy alias retained for existing modules that still reference JWT_SECRET_KEY.
JWT_SECRET_KEY = JWT_SIGNING_KEY
JWT_ALLOWED_ALGORITHMS = [JWT_ALGORITHM]
JWT_ACCESS_TOKEN_LIFETIME = 3600  # 1 hour in seconds
JWT_REFRESH_TOKEN_LIFETIME = 604800  # 7 days in seconds
# reCAPTCHA Configuration
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe')  # Default is Google's test key
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI')  # Default is Google's test key
RECAPTCHA_ENABLED = os.environ.get('RECAPTCHA_ENABLED', 'true').lower() == 'true'
# SimpleJWT configuration with refresh token rotation & blacklist
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=JWT_ACCESS_TOKEN_LIFETIME),
    "REFRESH_TOKEN_LIFETIME": timedelta(seconds=JWT_REFRESH_TOKEN_LIFETIME),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": JWT_ALGORITHM,
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "VERIFYING_KEY": JWT_VERIFYING_KEY,
    "ISSUER": JWT_ISSUER,
    "AUDIENCE": JWT_AUDIENCE,
}

# Rest Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Use our UnifiedJWTAuthentication globally to support both headers and secure cookies.
        'grc.jwt_auth.UnifiedJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # Secure-by-default: endpoints must be authenticated unless explicitly marked public.
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Framework-level: sanitize API exception responses and avoid stack trace leakage.
    'EXCEPTION_HANDLER': 'tprm_backend.utils.vendor_exception_handler.vendor_custom_exception_handler',
    # Throttling configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '10000/hour',
        'anon': '2000/hour',
        # Scoped throttle for incident exports to mitigate DoS by high request volume
        'export_incidents': '20/hour',
        # Audit write operations: max 10 creates per minute per authenticated user
        # Rationale: legitimate users rarely create more than a few audits per session;
        # this blocks automated DoS/spam scripts while not impacting real usage.
        'audit_write': '10/minute',
        # Notification write controls to mitigate alert spam.
        'notification_write': '30/minute',
        # Risk workflow write controls to prevent burst submission/assignment abuse.
        'risk_assignment': '20/minute',
        'risk_submission': '15/minute',
        'risk_review': '20/minute',
    },
    # Allow larger request size
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}
# Increase Django's data upload limit for large exports
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB (increased from 10MB)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# Maximum file upload size (for file uploads)
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB (increased from 10MB)
# S3 Microservice settings
S3_MICROSERVICE_URL = 'http://localhost:3000'  # Default URL for S3 microservice

# Report generation settings
REPORTS_DIR = Path(BASE_DIR) / 'Reports'
REPORTS_DIR.mkdir(exist_ok=True)  # Create Reports directory if it doesn't exist

# OpenAI API Configuration
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
# Optional complexity-tiered models for OpenAI-compatible providers (including NVIDIA)
OPENAI_MODEL_LIGHT = os.environ.get("OPENAI_MODEL_LIGHT", OPENAI_MODEL)
OPENAI_MODEL_MEDIUM = os.environ.get("OPENAI_MODEL_MEDIUM", OPENAI_MODEL)
OPENAI_MODEL_HEAVY = os.environ.get("OPENAI_MODEL_HEAVY", OPENAI_MODEL)
# NVIDIA-specific aliases (used when RISK_AI_PROVIDER=nvidia)
NVIDIA_MODEL_LIGHT = os.environ.get("NVIDIA_MODEL_LIGHT", os.environ.get("NVIDIA_MODEL", OPENAI_MODEL))
NVIDIA_MODEL_MEDIUM = os.environ.get("NVIDIA_MODEL_MEDIUM", os.environ.get("NVIDIA_MODEL", OPENAI_MODEL))
NVIDIA_MODEL_HEAVY = os.environ.get("NVIDIA_MODEL_HEAVY", os.environ.get("NVIDIA_MODEL", OPENAI_MODEL))

# Grok / xAI or other LLM provider
GROK_API_KEY = os.environ.get("GROK_API_KEY", "")
GROK_MODEL = os.environ.get("GROK_MODEL", "llama-3.1-8b-instant")



# Licensing toggle: allow disabling external license checks temporarily
LICENSE_CHECK_ENABLED = os.environ.get('LICENSE_CHECK_ENABLED', 'true').lower() == 'true'
# Increase Django's data upload limit for large exports
 
LICENSE_CHECK_ENABLED = False
 
# Ollama configuration
# Ollama configuration
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://13.126.18.17:11434')
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/2')
# Default timeout (seconds) for Ollama HTTP requests
OLLAMA_TIMEOUT = int(os.environ.get('OLLAMA_TIMEOUT', '600'))
# Default Ollama model to use (must exist on server per /api/tags)
# Recommended: Use quantized models for better performance (e.g., llama3.2:3b-instruct-q4_K_M)
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2:3b-instruct-q4_K_M')

# Risk AI Provider Selection
# Set to 'openai' or 'ollama' to choose which AI provider to use for risk document processing
# Default: 'ollama' if both are configured, else 'openai'
RISK_AI_PROVIDER = os.environ.get('RISK_AI_PROVIDER', 'ollama')

# ===== PASSWORD EXPIRY CONFIGURATION =====
# Password expiry in days (90 days)
PASSWORD_EXPIRY_DAYS = int(os.environ.get('PASSWORD_EXPIRY_DAYS', '90'))
# Days before expiry to send warning email (7 days before expiry)
PASSWORD_EXPIRY_WARNING_DAYS = int(os.environ.get('PASSWORD_EXPIRY_WARNING_DAYS', '7'))
# Number of previous passwords to check for reuse prevention (5 passwords)
PASSWORD_HISTORY_COUNT = int(os.environ.get('PASSWORD_HISTORY_COUNT', '5'))

# ===== LOGIN RATE LIMITING CONFIGURATION =====
# Login rate limiting per IP address (configurable for performance testing)
# TODO: Revert to '10' after KPMG performance testing is complete
LOGIN_RATE_LIMIT_PER_IP = int(os.environ.get('LOGIN_RATE_LIMIT_PER_IP', '200'))  # Currently set to 200 for KPMG testing (default was 10)
LOGIN_RATE_LIMIT_WINDOW_SECONDS = int(os.environ.get('LOGIN_RATE_LIMIT_WINDOW_SECONDS', '60'))  # Default: 60 seconds
# Comma-separated list of test IPs that should have higher limits (e.g., "192.168.1.100,10.0.0.50")
LOGIN_RATE_LIMIT_TEST_IPS = [ip.strip() for ip in os.environ.get('LOGIN_RATE_LIMIT_TEST_IPS', '').split(',') if ip.strip()] if os.environ.get('LOGIN_RATE_LIMIT_TEST_IPS') else []
# Multiplier for test IPs (e.g., 20 = 200 attempts/min for test IPs, while others remain at default)
LOGIN_RATE_LIMIT_TEST_MULTIPLIER = int(os.environ.get('LOGIN_RATE_LIMIT_TEST_MULTIPLIER', '1'))  # Default: 1 (no multiplier)

# =========================================================================
# USER INACTIVITY SETTINGS
# =========================================================================
# Number of days of inactivity before a user is automatically deactivated
# Users who haven't logged in for this many days will have their IsActive status changed to 'N'
# Default: 90 days (3 months)
USER_INACTIVITY_DAYS = int(os.environ.get('USER_INACTIVITY_DAYS', '90'))
# Whether to send email notifications to users before deactivation (future feature)
USER_INACTIVITY_EMAIL_ENABLED = os.environ.get('USER_INACTIVITY_EMAIL_ENABLED', 'false').lower() == 'true'
# Days before deactivation to send warning email (future feature)
USER_INACTIVITY_WARNING_DAYS = int(os.environ.get('USER_INACTIVITY_WARNING_DAYS', '7'))

# ===== EMAIL AND NOTIFICATION CONFIGURATION =====

# SMTP Configuration for Email
SMTP_SERVER = os.environ.get('SMTP_SERVER', 'smtp.gmail.com')
SMTP_PORT = int(os.environ.get('SMTP_PORT', '587'))
SMTP_EMAIL = os.environ.get('SMTP_EMAIL', '')
SMTP_PASSWORD = os.environ.get('SMTP_PASSWORD', '')

# Gmail Configuration
GMAIL_USER = os.environ.get('GMAIL_USER', '')
GMAIL_APP_PASSWORD = os.environ.get('GMAIL_APP_PASSWORD', '')

# Email Configuration
# For Azure AD: Use the Azure AD registered email (riskavaire@vardaanglobal.com)
# IMPORTANT: For Azure Graph API, DEFAULT_FROM_EMAIL must be an Azure AD registered email (e.g., @vardaanglobal.com)
# The AzureADEmailBackend will automatically use 'riskavaire@vardaanglobal.com' if a Gmail or non-Azure email is configured
# Priority: Environment variable > Azure AD default
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'riskavaire@vardaanglobal.com')
# Ensure we never use a Gmail address for Azure AD emails
if '@gmail.com' in DEFAULT_FROM_EMAIL.lower():
    DEFAULT_FROM_EMAIL = 'riskavaire@vardaanglobal.com'
    print(f"[SETTINGS] DEFAULT_FROM_EMAIL was Gmail, changed to Azure AD email: {DEFAULT_FROM_EMAIL}")
DEFAULT_FROM_NAME = os.environ.get('DEFAULT_FROM_NAME', 'GRC System')

# Django Email Backend Configuration
EMAIL_BACKEND = 'grc.routes.Global.azure_email_backend.AzureADEmailBackend'
EMAIL_HOST = SMTP_SERVER
EMAIL_PORT = SMTP_PORT
EMAIL_USE_TLS = True
EMAIL_HOST_USER = SMTP_EMAIL
EMAIL_HOST_PASSWORD = SMTP_PASSWORD
S3_MICRO_API_KEY = os.environ.get("S3_MICRO_API_KEY", "")

# Security alerting configuration (used by anomaly detector)
SECURITY_ALERT_EMAIL = os.environ.get('SECURITY_ALERT_EMAIL', '')
ALERT_USER_ON_LOGIN_ANOMALY = os.environ.get('ALERT_USER_ON_LOGIN_ANOMALY', 'true').lower() == 'true'

# Azure AD Email Configuration (no hardcoded secrets; configure via environment)
AZURE_AD_TENANT_ID = os.environ.get('AZURE_AD_TENANT_ID', '')
AZURE_AD_CLIENT_ID = os.environ.get('AZURE_AD_CLIENT_ID', '')
AZURE_AD_CLIENT_SECRET = os.environ.get('AZURE_AD_CLIENT_SECRET', '')
AZURE_AD_SCOPE = os.environ.get('AZURE_AD_SCOPE', 'https://graph.microsoft.com/.default')
# WhatsApp API Configuration
WHATSAPP_API_URL = os.environ.get('WHATSAPP_API_URL', 'https://graph.facebook.com/v21.0/521803094347148/messages')
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_SENDER_PHONE = os.environ.get('WHATSAPP_SENDER_PHONE', '')
TEMPLATE_NAME = os.environ.get('WHATSAPP_TEMPLATE_NAME', 'hello_world')

# AWS S3 Configuration
AWS_BUCKET_NAME = os.environ.get("AWS_BUCKET_NAME", "")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY", "")
AWS_REGION = os.environ.get("AWS_REGION", "ap-south-1")
AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "ap-south-1")
# Toggle between local and deployed environments (define early as it's used in other configs)
USE_LOCAL_DEVELOPMENT = os.environ.get('USE_LOCAL_DEVELOPMENT', 'true').lower() == 'true'  # Set to False for production

# In local development, it's common to run a single DB and/or not have access to the
# hosted TPRM RDS. If `TPRM_DB_HOST` is left as the default RDS hostname, Django will
# repeatedly attempt to connect and spam logs on every request (tenant middleware, etc.).
# To keep local dev usable, default TPRM host to the primary DB host in this case.
if USE_LOCAL_DEVELOPMENT:
    tprm_host_env = (os.environ.get("TPRM_DB_HOST") or "").strip()
    if (not tprm_host_env) or tprm_host_env.endswith(".rds.amazonaws.com"):
        DATABASES["tprm"]["HOST"] = os.environ.get("DB_HOST", DATABASES["tprm"]["HOST"])

# Helper function to clean environment variable values (remove quotes)
# Define early so it can be used in OAuth configurations
def clean_env_value(value, default=''):
    """Remove quotes from environment variable values"""
    if not value:
        return default
    value = str(value).strip()
    # Remove quotes from start and end
    while (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
        value = value[1:-1].strip()
    return value.strip("'\"")
# Microsoft Azure AD Configuration for Sentinel Integration
MICROSOFT_CLIENT_ID = os.environ.get("MICROSOFT_CLIENT_ID", "")
MICROSOFT_TENANT_ID = os.environ.get("MICROSOFT_TENANT_ID", "")
MICROSOFT_CLIENT_SECRET = os.environ.get("MICROSOFT_CLIENT_SECRET", "")
# Only use env var if explicitly set, otherwise use conditional based on USE_LOCAL_DEVELOPMENT
if 'MICROSOFT_REDIRECT_URI' in os.environ:
    REDIRECT_URI = clean_env_value(os.environ.get('MICROSOFT_REDIRECT_URI'))
else:
    REDIRECT_URI = (
        'http://localhost:8000/auth/sentinel/callback' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/auth/sentinel/callback'
    )
MICROSOFT_AUTHORITY = os.environ.get("MICROSOFT_AUTHORITY", "https://login.microsoftonline.com/common")
MICROSOFT_USER = os.environ.get("MICROSOFT_USER", "")

# Azure Sentinel Configuration
AZURE_SUBSCRIPTION_ID = os.environ.get("AZURE_SUBSCRIPTION_ID", "")
AZURE_RESOURCE_GROUP = os.environ.get("AZURE_RESOURCE_GROUP", "")
AZURE_WORKSPACE_NAME = os.environ.get("AZURE_WORKSPACE_NAME", "")

# Jira OAuth Configuration

JIRA_CLIENT_ID = clean_env_value(os.environ.get("JIRA_CLIENT_ID", ""))
JIRA_CLIENT_SECRET = clean_env_value(os.environ.get("JIRA_CLIENT_SECRET", ""))
# Only use env var if explicitly set, otherwise use conditional based on USE_LOCAL_DEVELOPMENT
if 'JIRA_REDIRECT_URI' in os.environ:
    JIRA_REDIRECT_URI = clean_env_value(os.environ.get('JIRA_REDIRECT_URI'))
else:
    JIRA_REDIRECT_URI = (
        'http://127.0.0.1:8000/api/jira/oauth-callback/' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/api/jira/oauth-callback'  # No trailing slash to match Atlassian registration
    )
JIRA_SCOPES = clean_env_value(os.environ.get("JIRA_SCOPES", 'read:jira-user read:jira-work'), 'read:jira-user read:jira-work')

# Database convenience env vars (for raw connections / other services)
DB_HOST = os.environ.get('DB_HOST', '')
DB_USER = os.environ.get('DB_USER', '')
DB_PASSWORD = os.environ.get('DB_PASSWORD', '')
DB_NAME = os.environ.get('DB_NAME', '')

BAMBOOHR_CLIENT_ID = clean_env_value(os.environ.get("BAMBOOHR_CLIENT_ID", ""))
BAMBOOHR_CLIENT_SECRET = clean_env_value(os.environ.get("BAMBOOHR_CLIENT_SECRET", ""))
# FRONTEND_URL: Prioritize local development setting
# If USE_LOCAL_DEVELOPMENT is True, always use localhost (even if FRONTEND_URL env var is set)
# This ensures Google OAuth redirects to local frontend when running locally
if USE_LOCAL_DEVELOPMENT:
    FRONTEND_URL = 'http://localhost:8080'  # Force localhost for local development
else:
    FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://example.com')

# Base URL for public questionnaire response links (email link; no login). Use hosted TPRM frontend in production.
PUBLIC_QUESTIONNAIRE_BASE_URL = os.environ.get(
    'PUBLIC_QUESTIONNAIRE_BASE_URL',
    'http://localhost:3000' if USE_LOCAL_DEVELOPMENT else 'http://riskavaire.vardaands.com'
).rstrip('/')
# Path under base URL for the public questionnaire response page. Must include /tprm/ in production so the TPRM frontend handles it (otherwise redirect to login).
PUBLIC_QUESTIONNAIRE_PATH = os.environ.get('PUBLIC_QUESTIONNAIRE_PATH', '/tprm/questionnaire-response-public')

# OFAC API for external screening (optional)
OFAC_API_KEY = os.environ.get('OFAC_API_KEY', '')
OFAC_API_BASE_URL = os.environ.get('OFAC_API_BASE_URL', 'https://api.ofac-api.com/v4')
# Allowed OFAC sources (for providers like ofac-api.com).
# Default: SDN only. You can override with env, e.g. OFAC_SOURCES="SDN,EU,UN"
OFAC_SOURCES = [
    s.strip() for s in os.environ.get('OFAC_SOURCES', 'SDN').split(',') if s.strip()
]

# SANCTIONS screening via external APIs
# Legacy/free option (sanctions.network) - still configurable, but not used by default now.
SANCTIONS_API_BASE_URL = os.environ.get('SANCTIONS_API_BASE_URL', 'https://sanctions.network')

# OpenSanctions matching API (preferred for SANCTIONS screening when API key is set)
OPENSANCTIONS_API_KEY = os.environ.get('OPENSANCTIONS_API_KEY', '')
OPENSANCTIONS_API_BASE_URL = os.environ.get('OPENSANCTIONS_API_BASE_URL', 'https://api.opensanctions.org')

# News providers for adverse media screening (optional)
NEWSAPI_API_KEY = os.environ.get('NEWSAPI_API_KEY', '')
NEWSAPI_BASE_URL = os.environ.get('NEWSAPI_BASE_URL', 'https://newsapi.org/v2')

GNEWS_API_KEY = os.environ.get('GNEWS_API_KEY', '')
GNEWS_BASE_URL = os.environ.get('GNEWS_BASE_URL', 'https://gnews.io/api/v4')

MEDIASTACK_API_KEY = os.environ.get('MEDIASTACK_API_KEY', '')
MEDIASTACK_BASE_URL = os.environ.get('MEDIASTACK_BASE_URL', 'http://api.mediastack.com/v1')
if 'BAMBOOHR_REDIRECT_URI' in os.environ:
    BAMBOOHR_REDIRECT_URI = clean_env_value(os.environ.get('BAMBOOHR_REDIRECT_URI'))
else:
    BAMBOOHR_REDIRECT_URI = (
        'http://127.0.0.1:8000/api/bamboohr/oauth-callback/' if USE_LOCAL_DEVELOPMENT
        else 'https://grc-backend.vardaands.com/api/bamboohr/oauth-callback/'
    )
 
BAMBOOHR_FLASK_SERVER_URL = os.environ.get(
    'BAMBOOHR_FLASK_SERVER_URL',
    'http://127.0.0.1:5000' if USE_LOCAL_DEVELOPMENT else 'https://grc-backend.vardaands.com'
)

BAMBOOHR_SCOPES = clean_env_value(
    os.environ.get('BAMBOOHR_SCOPES', 'email openid employee company:info employee:contact employee:job employee:name employee:photo employee_directory'),
    'email openid employee company:info employee:contact employee:job employee:name employee:photo employee_directory'
)
 
# Google OAuth Configuration for SSO
GOOGLE_CLIENT_ID = clean_env_value(os.environ.get("GOOGLE_CLIENT_ID", ""))
GOOGLE_CLIENT_SECRET = clean_env_value(os.environ.get("GOOGLE_CLIENT_SECRET", ""))
# GOOGLE_REDIRECT_URI: Prioritize local development setting
# If USE_LOCAL_DEVELOPMENT is True, always use localhost (even if GOOGLE_REDIRECT_URI env var is set)
# This ensures Google OAuth redirects to local backend when running locally
if USE_LOCAL_DEVELOPMENT:
    GOOGLE_REDIRECT_URI = 'http://localhost:8000/api/google/oauth-callback/'  # Force localhost for local development
else:
    # In production, use env var if set, otherwise use production URL
    if 'GOOGLE_REDIRECT_URI' in os.environ:
        GOOGLE_REDIRECT_URI = clean_env_value(os.environ.get('GOOGLE_REDIRECT_URI'))
    else:
        GOOGLE_REDIRECT_URI = 'https://grc-backend.vardaands.com/api/google/oauth-callback/'
GOOGLE_SCOPES = clean_env_value(
    os.environ.get('GOOGLE_SCOPES', 'openid email profile'),
    'openid email profile'
)
 
 
 
 

 
# OAuth State Verification (set to 'true' to skip in development)
# WARNING: Only use this in local development! Always verify state in production
SKIP_OAUTH_STATE_VERIFICATION = os.environ.get('SKIP_OAUTH_STATE_VERIFICATION', 'true' if DEBUG else 'false')

# -----------------------------------------------------------------------------
# Redirect Allowlist for Server-side Redirects (prevents open redirects)
# -----------------------------------------------------------------------------
from urllib.parse import urlparse as _urlparse  # local import to avoid top pollution
_fe = os.environ.get('FRONTEND_URL', 'http://localhost:8080')
try:
    _fe_host = _urlparse(_fe).hostname
except Exception:
    _fe_host = None
REDIRECT_ALLOWLIST_HOSTS = _env_csv("REDIRECT_ALLOWLIST_HOSTS", _fe_host or "")
# Enforce on all API and OAuth paths, including versioned GRC prefix
REDIRECT_ENFORCE_ON_PREFIXES = _env_csv("REDIRECT_ENFORCE_ON_PREFIXES", "/api/,/api/v1/,/api/v1/grc/,/oauth/")

# -----------------------------------------------------------------------------
# Request Signature / Replay Protection
# -----------------------------------------------------------------------------
REQUEST_SIGNATURE_ENABLED = _env_bool("REQUEST_SIGNATURE_ENABLED", False)
REQUEST_SIGNATURE_SECRET = os.environ.get("REQUEST_SIGNATURE_SECRET", "")
REQUEST_SIGNATURE_TOLERANCE_SECONDS = int(os.environ.get("REQUEST_SIGNATURE_TOLERANCE_SECONDS", "300"))
# Enforce signatures for all mutating methods and GET by default (defense-in-depth)
REQUEST_SIGNATURE_ENFORCE_METHODS = _env_csv("REQUEST_SIGNATURE_ENFORCE_METHODS", "POST,PUT,PATCH,DELETE")
REQUEST_SIGNATURE_EXEMPT_PATH_PREFIXES = _env_csv(
    "REQUEST_SIGNATURE_EXEMPT_PATH_PREFIXES",
    # Keep exemptions narrow: public auth bootstrap and static/admin. Do NOT exempt whole API trees.
    "/admin/,/static/,/media/,/api/login/,/api/jwt/,/api/register/,/api/send-otp/,/api/verify-otp/,/api/reset-password/,/api/google/,/api/gmail/,/oauth/"
)

# MFA Configuration
# Set MFA_ENABLED=true to enable Multi-Factor Authentication, false to disable
MFA_ENABLED = os.environ.get('MFA_ENABLED', 'true').lower() == 'true'

# Force MFA for all users regardless of MFA_ENABLED (used to enforce MFA for privileged/external)
FORCE_MFA_FOR_ALL = os.environ.get('FORCE_MFA_FOR_ALL', 'true').lower() == 'true'
 


# Set environment variables so they can be accessed via os.getenv() by notification_service.py
os.environ.setdefault('DB_HOST', DB_HOST)
os.environ.setdefault('DB_USER', DB_USER)
os.environ.setdefault('DB_PASSWORD', DB_PASSWORD)
os.environ.setdefault('DB_NAME', DB_NAME)

os.environ.setdefault('SMTP_SERVER', SMTP_SERVER)
os.environ.setdefault('SMTP_PORT', str(SMTP_PORT))
os.environ.setdefault('SMTP_EMAIL', SMTP_EMAIL)
os.environ.setdefault('SMTP_PASSWORD', SMTP_PASSWORD)

os.environ.setdefault('GMAIL_USER', GMAIL_USER)
os.environ.setdefault('GMAIL_APP_PASSWORD', GMAIL_APP_PASSWORD)

os.environ.setdefault('DEFAULT_FROM_EMAIL', DEFAULT_FROM_EMAIL)
os.environ.setdefault('DEFAULT_FROM_NAME', DEFAULT_FROM_NAME)

os.environ.setdefault('WHATSAPP_PHONE_NUMBER_ID', WHATSAPP_PHONE_NUMBER_ID)
os.environ.setdefault('WHATSAPP_ACCESS_TOKEN', WHATSAPP_ACCESS_TOKEN)
os.environ.setdefault('WHATSAPP_SENDER_PHONE', WHATSAPP_SENDER_PHONE)

os.environ.setdefault('AWS_ACCESS_KEY_ID', AWS_ACCESS_KEY_ID)
os.environ.setdefault('AWS_SECRET_ACCESS_KEY', AWS_SECRET_ACCESS_KEY)
os.environ.setdefault('AWS_STORAGE_BUCKET_NAME', AWS_STORAGE_BUCKET_NAME)
os.environ.setdefault('AWS_S3_REGION_NAME', AWS_S3_REGION_NAME)

os.environ.setdefault('MICROSOFT_CLIENT_ID', MICROSOFT_CLIENT_ID)
os.environ.setdefault('MICROSOFT_CLIENT_SECRET', MICROSOFT_CLIENT_SECRET)
os.environ.setdefault('MICROSOFT_TENANT_ID', MICROSOFT_TENANT_ID)
os.environ.setdefault('MICROSOFT_AUTHORITY', MICROSOFT_AUTHORITY)
os.environ.setdefault('MICROSOFT_USER', MICROSOFT_USER)

os.environ.setdefault('JIRA_CLIENT_ID', JIRA_CLIENT_ID)
os.environ.setdefault('JIRA_CLIENT_SECRET', JIRA_CLIENT_SECRET)
os.environ.setdefault('JIRA_REDIRECT_URI', JIRA_REDIRECT_URI)
os.environ.setdefault('JIRA_SCOPES', JIRA_SCOPES)
os.environ.setdefault('FRONTEND_URL', FRONTEND_URL)

os.environ.setdefault('BAMBOOHR_CLIENT_ID', BAMBOOHR_CLIENT_ID)
os.environ.setdefault('BAMBOOHR_CLIENT_SECRET', BAMBOOHR_CLIENT_SECRET)
os.environ.setdefault('BAMBOOHR_REDIRECT_URI', BAMBOOHR_REDIRECT_URI)
os.environ.setdefault('BAMBOOHR_SCOPES', BAMBOOHR_SCOPES)
os.environ.setdefault('USE_LOCAL_DEVELOPMENT', str(USE_LOCAL_DEVELOPMENT))
os.environ.setdefault('BAMBOOHR_FLASK_SERVER_URL', BAMBOOHR_FLASK_SERVER_URL)
os.environ.setdefault('SKIP_OAUTH_STATE_VERIFICATION', SKIP_OAUTH_STATE_VERIFICATION)

os.environ.setdefault('GOOGLE_CLIENT_ID', GOOGLE_CLIENT_ID)
os.environ.setdefault('GOOGLE_CLIENT_SECRET', GOOGLE_CLIENT_SECRET)
os.environ.setdefault('GOOGLE_REDIRECT_URI', GOOGLE_REDIRECT_URI)
os.environ.setdefault('GOOGLE_SCOPES', GOOGLE_SCOPES)

# Log Google OAuth configuration at startup (for debugging)
import logging
logger = logging.getLogger(__name__)
logger.info("=" * 60)
logger.info("🔧 GOOGLE OAUTH CONFIGURATION:")
logger.info(f"   USE_LOCAL_DEVELOPMENT: {USE_LOCAL_DEVELOPMENT}")
logger.info(f"   GOOGLE_REDIRECT_URI: {GOOGLE_REDIRECT_URI}")
logger.info(f"   FRONTEND_URL: {FRONTEND_URL}")
logger.info(f"   GOOGLE_CLIENT_ID: {'***SET***' if GOOGLE_CLIENT_ID else 'NOT SET'}")
logger.info(f"   GOOGLE_CLIENT_SECRET: {'***SET***' if GOOGLE_CLIENT_SECRET else 'NOT SET'}")
logger.info("=" * 60)

# Redis configuration for Phase 2 AI caching
os.environ.setdefault('REDIS_URL', REDIS_URL)

# =========================================================================
# CELERY CONFIGURATION (for scheduled tasks like retention deletion)
# =========================================================================
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Ollama configuration (fallback)
OLLAMA_BASE_URL = os.environ.get('OLLAMA_BASE_URL', 'http://13.126.18.17:11434')
# Default timeout (seconds) for Ollama HTTP requests
OLLAMA_TIMEOUT = int(os.environ.get('OLLAMA_TIMEOUT', '600'))
# Default Ollama model to use (must exist on server per /api/tags)
OLLAMA_MODEL = os.environ.get('OLLAMA_MODEL', 'llama3.2:3b')
# AI consistency settings for reproducible results
OLLAMA_TEMPERATURE = float(os.environ.get('OLLAMA_TEMPERATURE', '0.1'))  # Low temperature for consistency
OLLAMA_SEED = int(os.environ.get('OLLAMA_SEED', '42'))  # Fixed seed for reproducibility

# =========================================================================
# SUPPRESS DJANGO RUNSERVER WARNINGS - Monkey patch sys.stderr
# =========================================================================
class _StderrFilter:
    """Filter out Django development server warnings"""
    def __init__(self, original):
        self._original = original
        
    def write(self, message):
        # Skip warning messages
        if any(phrase in message for phrase in [
            'WARNING: This is a development server',
            'Do not use it in a production setting',
            'For more information on production servers see',
            'https://docs.djangoproject.com/en'
        ]):
            return
        return self._original.write(message)
    
    def flush(self):
        return self._original.flush()
    
    def __getattr__(self, name):
        return getattr(self._original, name)

# Apply the filter to sys.stderr
if 'runserver' in sys.argv:
    sys.stderr = _StderrFilter(sys.stderr)