# Generated by Django 5.0.14 on 2026-01-05 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rfp", "0016_add_org_field"),
        ("rfp", "0023_rename_auto_publish_to_auto_approve"),
    ]

    operations = []
