# Generated by Django 5.0.14 on 2026-04-23 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grc', '0004_users_add_identifier_hashes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='audit',
            name='audits_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='compliance',
            name='compliances_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='framework',
            name='frameworks_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='incidents_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='policy',
            name='policies_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='risk',
            name='risks_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='users',
            name='users_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_Subdoma_cb0ff0_idx',
            old_name='tenants_subdomain_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_License_5102ad_idx',
            old_name='tenants_license_key_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_Status_6cbcde_idx',
            old_name='tenants_status_idx',
        ),
        migrations.AlterField(
            model_name='audit',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='TenantId', help_text='Tenant this audit belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='grc.tenant'),
        ),
        migrations.AlterField(
            model_name='compliance',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='TenantId', help_text='Tenant this compliance belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='grc.tenant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='TenantId', help_text='Tenant this department belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='grc.tenant'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='tenant',
            field=models.ForeignKey(blank=True, db_column='TenantId', help_text='Tenant this risk belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk', to='grc.tenant'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
