# Generated by Django 5.1 on 2025-09-15 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncidentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IncidentId", models.IntegerField()),
                ("version", models.CharField(max_length=45)),
                ("ExtractedInfo", models.JSONField(null=True)),
                ("AssigneeId", models.CharField(max_length=45, null=True)),
                ("ReviewerId", models.CharField(max_length=45, null=True)),
                ("ApprovedRejected", models.CharField(max_length=45, null=True)),
                ("Date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "incident_approval",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RiskApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("RiskInstanceId", models.IntegerField()),
                ("version", models.CharField(max_length=45)),
                ("ExtractedInfo", models.JSONField(null=True)),
                ("UserId", models.CharField(max_length=45, null=True)),
                ("ApproverId", models.CharField(max_length=45, null=True)),
                ("ApprovedRejected", models.CharField(max_length=45, null=True)),
                ("Date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "grc.risk_approval",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RiskInstance",
            fields=[
                ("RiskInstanceId", models.AutoField(primary_key=True, serialize=False)),
                ("RiskId", models.IntegerField(null=True)),
                ("IncidentId", models.IntegerField(null=True)),
                ("ComplianceId", models.IntegerField(null=True)),
                ("RiskTitle", models.TextField(null=True)),
                ("RiskDescription", models.TextField(null=True)),
                ("PossibleDamage", models.TextField(null=True)),
                ("RiskPriority", models.CharField(max_length=50, null=True)),
                ("Criticality", models.CharField(max_length=100, null=True)),
                ("Category", models.CharField(max_length=100, null=True)),
                ("Origin", models.CharField(max_length=50, null=True)),
                ("ReportedBy", models.IntegerField(null=True)),
                ("RiskLikelihood", models.IntegerField(null=True)),
                ("RiskImpact", models.IntegerField(null=True)),
                ("RiskExposureRating", models.IntegerField(null=True)),
                ("Appetite", models.CharField(max_length=100, null=True)),
                ("RiskResponseType", models.CharField(max_length=100, null=True)),
                ("RiskResponseDescription", models.TextField(null=True)),
                ("RiskMitigation", models.JSONField(blank=True, null=True)),
                ("RiskType", models.TextField(null=True)),
                ("RiskOwner", models.CharField(max_length=255, null=True)),
                ("BusinessImpact", models.TextField(null=True)),
                ("UserId", models.IntegerField(null=True)),
                ("MitigationDueDate", models.DateField(null=True)),
                ("ModifiedMitigations", models.JSONField(null=True)),
                ("MitigationCompletedDate", models.DateField(null=True)),
                ("ReviewerCount", models.IntegerField(null=True)),
                ("RiskFormDetails", models.JSONField(blank=True, null=True)),
                ("RecurrenceCount", models.IntegerField(default=1, null=True)),
                ("CreatedAt", models.DateField(auto_now_add=True)),
                ("Reviewer", models.CharField(max_length=45, null=True)),
                ("ReviewerId", models.IntegerField(null=True)),
                ("FirstResponseAt", models.DateTimeField(null=True)),
                (
                    "RiskStatus",
                    models.CharField(
                        choices=[
                            ("Not Assigned", "Not Assigned"),
                            ("Assigned", "Assigned"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Not Assigned",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "MitigationStatus",
                    models.CharField(
                        choices=[
                            ("Yet to Start", "Yet to Start"),
                            ("Work In Progress", "Work In Progress"),
                            (
                                "Revision Required by Reviewer",
                                "Revision Required by Reviewer",
                            ),
                            ("Revision Required by User", "Revision Required by User"),
                            ("Completed", "Completed"),
                        ],
                        default="Yet to Start",
                        max_length=45,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "risk_instance",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Applicability",
            fields=[
                (
                    "ApplicabilityId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("EntityId", models.IntegerField()),
                ("DepartmentId", models.IntegerField()),
                ("CategoryId", models.IntegerField()),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField(blank=True, null=True)),
                ("IsMandatory", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "applicability",
            },
        ),
        migrations.CreateModel(
            name="AWSCredentials",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("accessKey", models.CharField(max_length=145)),
                ("secretKey", models.CharField(max_length=145)),
                ("region", models.CharField(max_length=45)),
                ("bucketName", models.CharField(max_length=45)),
                ("microServiceUrl", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name": "AWS Credential",
                "verbose_name_plural": "AWS Credentials",
                "db_table": "aws_credentials",
            },
        ),
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                ("BusinessUnitId", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Code", models.CharField(max_length=50)),
                ("Description", models.TextField()),
                ("EntityId", models.IntegerField()),
                ("IsActive", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField()),
            ],
            options={
                "db_table": "businessunits",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("CategoryId", models.AutoField(primary_key=True, serialize=False)),
                ("CategoryName", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("IsActive", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="CategoryBusinessUnit",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "categoryunit",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("DepartmentId", models.AutoField(primary_key=True, serialize=False)),
                ("EntityId", models.IntegerField()),
                ("DepartmentName", models.CharField(max_length=255)),
                ("DepartmentHead", models.IntegerField()),
                ("IsActive", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField()),
                ("BusinessUnitId", models.IntegerField()),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("EntityName", models.CharField(max_length=255)),
                ("EntityType", models.CharField(max_length=255)),
                ("ParentEntityId", models.IntegerField(blank=True, null=True)),
                ("LocationId", models.IntegerField()),
                ("IsActive", models.BooleanField(default=True)),
                ("CreatedDate", models.DateTimeField()),
            ],
            options={
                "db_table": "mainentities",
            },
        ),
        migrations.CreateModel(
            name="ExportTask",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("export_data", models.JSONField(blank=True, null=True)),
                ("file_type", models.CharField(max_length=10)),
                ("user_id", models.CharField(max_length=100)),
                ("s3_url", models.CharField(blank=True, max_length=255, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "exported_files",
            },
        ),
        migrations.CreateModel(
            name="ExternalApplication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("category", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon_class", models.CharField(max_length=100)),
                ("version", models.CharField(default="v1.0.0", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("pending", "Pending"),
                            ("error", "Error"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, null=True)),
                (
                    "api_endpoint",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("oauth_url", models.URLField(blank=True, max_length=500, null=True)),
                ("features", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "external-applications",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Framework",
            fields=[
                ("FrameworkId", models.AutoField(primary_key=True, serialize=False)),
                ("FrameworkName", models.CharField(max_length=255)),
                ("CurrentVersion", models.FloatField(default=1.0)),
                ("FrameworkDescription", models.TextField()),
                ("EffectiveDate", models.DateField(blank=True, null=True)),
                ("CreatedByName", models.CharField(max_length=255)),
                ("CreatedByDate", models.DateField()),
                ("Category", models.CharField(blank=True, max_length=100, null=True)),
                ("DocURL", models.CharField(blank=True, max_length=255, null=True)),
                ("Identifier", models.CharField(blank=True, max_length=45, null=True)),
                ("StartDate", models.DateField(blank=True, null=True)),
                ("EndDate", models.DateField(blank=True, null=True)),
                ("Status", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "ActiveInactive",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("Reviewer", models.CharField(max_length=255)),
                (
                    "InternalExternal",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={
                "db_table": "frameworks",
            },
        ),
        migrations.CreateModel(
            name="GRCLog",
            fields=[
                ("LogId", models.AutoField(primary_key=True, serialize=False)),
                ("Timestamp", models.DateTimeField(auto_now_add=True)),
                ("UserId", models.CharField(max_length=50, null=True)),
                ("UserName", models.CharField(max_length=100, null=True)),
                ("Module", models.CharField(max_length=100, null=True)),
                ("ActionType", models.CharField(max_length=50, null=True)),
                ("EntityId", models.CharField(max_length=50, null=True)),
                ("EntityType", models.CharField(max_length=50, null=True)),
                ("LogLevel", models.CharField(default="INFO", max_length=20)),
                ("Description", models.TextField(null=True)),
                ("IPAddress", models.CharField(max_length=45, null=True)),
                ("AdditionalInfo", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "grc_logs",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("HolidayId", models.AutoField(primary_key=True, serialize=False)),
                ("EntityId", models.IntegerField()),
                ("HolidayDate", models.DateField()),
                ("HolidayName", models.CharField(max_length=255)),
                ("IsNational", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "holidays",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("LocationID", models.AutoField(primary_key=True, serialize=False)),
                ("AddressLine", models.CharField(max_length=255)),
                ("City", models.CharField(max_length=255)),
                ("State", models.CharField(blank=True, max_length=255, null=True)),
                ("Country", models.CharField(max_length=255)),
                ("PostalCode", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "locations",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("recipient", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=100)),
                ("channel", models.CharField(max_length=20)),
                ("success", models.BooleanField()),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("RiskId", models.AutoField(primary_key=True, serialize=False)),
                ("ComplianceId", models.IntegerField(null=True)),
                ("RiskTitle", models.TextField(null=True)),
                ("Criticality", models.CharField(max_length=50, null=True)),
                ("PossibleDamage", models.TextField(null=True)),
                ("Category", models.CharField(max_length=100, null=True)),
                ("RiskType", models.TextField(null=True)),
                ("BusinessImpact", models.TextField(null=True)),
                ("RiskDescription", models.TextField(null=True)),
                ("RiskLikelihood", models.IntegerField(null=True)),
                ("RiskImpact", models.IntegerField(null=True)),
                ("RiskExposureRating", models.IntegerField(null=True)),
                ("RiskPriority", models.CharField(max_length=50, null=True)),
                ("RiskMitigation", models.TextField(null=True)),
                ("CreatedAt", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "risk",
            },
        ),
        migrations.CreateModel(
            name="S3File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField()),
                ("file_type", models.CharField(blank=True, max_length=50, null=True)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("user_id", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "s3_files",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("UserId", models.AutoField(primary_key=True, serialize=False)),
                ("UserName", models.CharField(max_length=255)),
                ("Password", models.CharField(max_length=255)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                ("Email", models.EmailField(max_length=100)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                (
                    "IsActive",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")], default="Y", max_length=1
                    ),
                ),
                ("DepartmentId", models.CharField(max_length=50)),
                (
                    "session_token",
                    models.CharField(blank=True, max_length=1045, null=True),
                ),
                (
                    "consent_accepted",
                    models.CharField(
                        choices=[("0", "Not Accepted"), ("1", "Accepted")],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "license_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AuditVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AuditId", models.IntegerField()),
                ("Version", models.CharField(max_length=45)),
                ("ExtractedInfo", models.JSONField()),
                ("UserId", models.IntegerField()),
                (
                    "ApprovedRejected",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("Date", models.DateTimeField(auto_now_add=True)),
                ("ActiveInactive", models.CharField(default="1", max_length=1)),
            ],
            options={
                "db_table": "audit_version",
                "unique_together": {("AuditId", "Version")},
            },
        ),
        migrations.CreateModel(
            name="FrameworkApproval",
            fields=[
                ("ApprovalId", models.AutoField(primary_key=True, serialize=False)),
                ("ExtractedData", models.JSONField(blank=True, null=True)),
                ("UserId", models.IntegerField()),
                ("ReviewerId", models.IntegerField(blank=True, null=True)),
                ("Version", models.CharField(blank=True, max_length=50, null=True)),
                ("ApprovedNot", models.BooleanField(null=True)),
                ("ApprovedDate", models.DateField(blank=True, null=True)),
                (
                    "FrameworkId",
                    models.ForeignKey(
                        db_column="FrameworkId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.framework",
                    ),
                ),
            ],
            options={
                "db_table": "frameworkapproval",
            },
        ),
        migrations.CreateModel(
            name="FrameworkVersion",
            fields=[
                ("VersionId", models.AutoField(primary_key=True, serialize=False)),
                ("Version", models.FloatField()),
                ("FrameworkName", models.CharField(max_length=255)),
                ("CreatedBy", models.CharField(max_length=255)),
                ("CreatedDate", models.DateField()),
                ("PreviousVersionId", models.IntegerField(blank=True, null=True)),
                (
                    "FrameworkId",
                    models.ForeignKey(
                        db_column="FrameworkId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.framework",
                    ),
                ),
            ],
            options={
                "db_table": "frameworkversions",
            },
        ),
        migrations.CreateModel(
            name="LastChecklistItemVerified",
            fields=[
                (
                    "ComplianceId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("SubPolicyId", models.IntegerField()),
                ("PolicyId", models.IntegerField()),
                ("FrameworkId", models.IntegerField()),
                ("Date", models.DateField(blank=True, null=True)),
                ("Time", models.TimeField(blank=True, null=True)),
                ("User", models.IntegerField(blank=True, null=True)),
                ("Complied", models.CharField(blank=True, max_length=1, null=True)),
                ("Comments", models.TextField(blank=True, null=True)),
                ("Count", models.IntegerField(blank=True, default=0, null=True)),
                ("AuditFindingsId", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "lastchecklistitemverified",
                "unique_together": {
                    ("ComplianceId", "SubPolicyId", "PolicyId", "FrameworkId")
                },
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                ("PolicyId", models.AutoField(primary_key=True, serialize=False)),
                ("CurrentVersion", models.CharField(default="1.0", max_length=20)),
                ("Status", models.CharField(max_length=50)),
                ("PolicyDescription", models.TextField()),
                ("PolicyName", models.CharField(max_length=255)),
                ("StartDate", models.DateField()),
                ("EndDate", models.DateField(blank=True, null=True)),
                ("Department", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "CreatedByName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("CreatedByDate", models.DateField(blank=True, null=True)),
                (
                    "Applicability",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("DocURL", models.CharField(blank=True, max_length=255, null=True)),
                ("Scope", models.TextField(blank=True, null=True)),
                ("Objective", models.TextField(blank=True, null=True)),
                ("Identifier", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "PermanentTemporary",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "ActiveInactive",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("CoverageRate", models.FloatField(blank=True, null=True)),
                (
                    "AcknowledgedUserIds",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("AcknowledgementCount", models.IntegerField(default=0)),
                ("PolicyType", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "PolicyCategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "PolicySubCategory",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Reviewer", models.CharField(blank=True, max_length=255, null=True)),
                ("Entities", models.JSONField(blank=True, default=list, null=True)),
                (
                    "FrameworkId",
                    models.ForeignKey(
                        db_column="FrameworkId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.framework",
                    ),
                ),
            ],
            options={
                "db_table": "policies",
            },
        ),
        migrations.CreateModel(
            name="ComplianceApproval",
            fields=[
                ("ApprovalId", models.AutoField(primary_key=True, serialize=False)),
                ("Identifier", models.CharField(db_column="Identifier", max_length=45)),
                ("ExtractedData", models.JSONField(blank=True, null=True)),
                ("UserId", models.IntegerField()),
                ("ReviewerId", models.IntegerField()),
                ("Version", models.CharField(blank=True, max_length=50, null=True)),
                ("ApprovedNot", models.BooleanField(null=True)),
                ("ApprovedDate", models.DateField(blank=True, null=True)),
                ("ApprovalDueDate", models.DateField(blank=True, null=True)),
                (
                    "PolicyId",
                    models.ForeignKey(
                        blank=True,
                        db_column="PolicyId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.policy",
                    ),
                ),
            ],
            options={
                "db_table": "complianceapproval",
            },
        ),
        migrations.CreateModel(
            name="Audit",
            fields=[
                ("AuditId", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(blank=True, max_length=255, null=True)),
                ("Scope", models.TextField(blank=True, null=True)),
                ("Objective", models.TextField(blank=True, null=True)),
                (
                    "BusinessUnit",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Role", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "Responsibility",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("DueDate", models.DateField()),
                ("Frequency", models.IntegerField(null=True)),
                ("Status", models.CharField(max_length=45)),
                ("CompletionDate", models.DateTimeField(null=True)),
                ("ReviewStatus", models.CharField(max_length=45, null=True)),
                ("ReviewerComments", models.CharField(max_length=255, null=True)),
                ("AuditType", models.CharField(max_length=1)),
                ("Evidence", models.TextField(blank=True, null=True)),
                ("Comments", models.TextField(blank=True, null=True)),
                (
                    "AssignedDate",
                    models.DateTimeField(db_column="AssignedDate", null=True),
                ),
                ("Reports", models.JSONField(blank=True, null=True)),
                ("ReviewStartDate", models.DateTimeField(null=True)),
                ("ReviewDate", models.DateTimeField(null=True)),
                (
                    "FrameworkId",
                    models.ForeignKey(
                        db_column="FrameworkId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.framework",
                    ),
                ),
                (
                    "PolicyId",
                    models.ForeignKey(
                        db_column="PolicyId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.policy",
                    ),
                ),
            ],
            options={
                "db_table": "audit",
            },
        ),
        migrations.CreateModel(
            name="PolicyApproval",
            fields=[
                ("ApprovalId", models.AutoField(primary_key=True, serialize=False)),
                ("Identifier", models.CharField(db_column="Identifier", max_length=45)),
                ("ExtractedData", models.JSONField(blank=True, null=True)),
                ("UserId", models.IntegerField()),
                ("ReviewerId", models.IntegerField()),
                ("Version", models.CharField(blank=True, max_length=50, null=True)),
                ("ApprovedNot", models.BooleanField(null=True)),
                ("ApprovedDate", models.DateField(blank=True, null=True)),
                ("ApprovalDueDate", models.DateField(blank=True, null=True)),
                (
                    "PolicyId",
                    models.ForeignKey(
                        blank=True,
                        db_column="PolicyId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.policy",
                    ),
                ),
            ],
            options={
                "db_table": "policyapproval",
            },
        ),
        migrations.CreateModel(
            name="PolicyCategory",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("PolicyType", models.CharField(max_length=255)),
                ("PolicyCategory", models.CharField(max_length=255)),
                ("PolicySubCategory", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "policycategories",
                "unique_together": {
                    ("PolicyType", "PolicyCategory", "PolicySubCategory")
                },
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                ("VersionId", models.AutoField(primary_key=True, serialize=False)),
                ("Version", models.CharField(max_length=20)),
                ("PolicyName", models.CharField(max_length=255)),
                ("CreatedBy", models.CharField(max_length=255)),
                ("CreatedDate", models.DateField()),
                ("PreviousVersionId", models.IntegerField(blank=True, null=True)),
                (
                    "PolicyId",
                    models.ForeignKey(
                        db_column="PolicyId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.policy",
                    ),
                ),
            ],
            options={
                "db_table": "policyversions",
            },
        ),
        migrations.CreateModel(
            name="SubPolicy",
            fields=[
                ("SubPolicyId", models.AutoField(primary_key=True, serialize=False)),
                ("SubPolicyName", models.CharField(max_length=255)),
                ("CreatedByName", models.CharField(max_length=255)),
                ("CreatedByDate", models.DateField()),
                ("Identifier", models.CharField(max_length=45)),
                ("Description", models.TextField()),
                ("Status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "PermanentTemporary",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Control", models.TextField(blank=True, null=True)),
                (
                    "PolicyId",
                    models.ForeignKey(
                        db_column="PolicyId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.policy",
                    ),
                ),
            ],
            options={
                "db_table": "subpolicies",
            },
        ),
        migrations.CreateModel(
            name="Compliance",
            fields=[
                ("ComplianceId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ComplianceTitle",
                    models.CharField(blank=True, max_length=145, null=True),
                ),
                ("ComplianceItemDescription", models.TextField(blank=True, null=True)),
                (
                    "ComplianceType",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Scope", models.TextField(blank=True, null=True)),
                ("Objective", models.TextField(blank=True, null=True)),
                (
                    "BusinessUnitsCovered",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("IsRisk", models.BooleanField(blank=True, null=True)),
                ("PossibleDamage", models.TextField(blank=True, null=True)),
                ("mitigation", models.JSONField(blank=True, null=True)),
                ("Criticality", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "MandatoryOptional",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ManualAutomatic",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("Impact", models.CharField(blank=True, max_length=50, null=True)),
                ("Probability", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "MaturityLevel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Initial", "Initial"),
                            ("Developing", "Developing"),
                            ("Defined", "Defined"),
                            ("Managed", "Managed"),
                            ("Optimizing", "Optimizing"),
                        ],
                        default="Initial",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "ActiveInactive",
                    models.CharField(
                        blank=True, default="Inactive", max_length=45, null=True
                    ),
                ),
                (
                    "PermanentTemporary",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "CreatedByName",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("CreatedByDate", models.DateField(blank=True, null=True)),
                ("ComplianceVersion", models.CharField(max_length=50)),
                (
                    "Status",
                    models.CharField(
                        blank=True, default="Under Review", max_length=50, null=True
                    ),
                ),
                ("Identifier", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "Applicability",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("PotentialRiskScenarios", models.TextField(blank=True, null=True)),
                (
                    "RiskType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Current", "Current"),
                            ("Residual", "Residual"),
                            ("Inherent", "Inherent"),
                            ("Emerging", "Emerging"),
                            ("Accepted", "Accepted"),
                        ],
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "RiskCategory",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "RiskBusinessImpact",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                (
                    "PreviousComplianceVersionId",
                    models.ForeignKey(
                        blank=True,
                        db_column="PreviousComplianceVersionId",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="grc.compliance",
                    ),
                ),
                (
                    "SubPolicy",
                    models.ForeignKey(
                        db_column="SubPolicyId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliances",
                        to="grc.subpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "compliance",
            },
        ),
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                ("ReportId", models.AutoField(primary_key=True, serialize=False)),
                ("Report", models.TextField()),
                (
                    "AuditId",
                    models.ForeignKey(
                        db_column="AuditId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.audit",
                    ),
                ),
                (
                    "FrameworkId",
                    models.ForeignKey(
                        db_column="FrameworkId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.framework",
                    ),
                ),
                (
                    "PolicyId",
                    models.ForeignKey(
                        db_column="PolicyId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.policy",
                    ),
                ),
                (
                    "SubPolicyId",
                    models.ForeignKey(
                        db_column="SubPolicyId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.subpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "audit_report",
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="SubPolicyId",
            field=models.ForeignKey(
                db_column="SubPolicyId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grc.subpolicy",
            ),
        ),
        migrations.CreateModel(
            name="RiskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="grc.risk",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assignments_created",
                        to="grc.users",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grc.users"
                    ),
                ),
            ],
            options={
                "db_table": "risk_assignments",
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("IncidentId", models.AutoField(primary_key=True, serialize=False)),
                ("IncidentTitle", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Mitigation", models.JSONField(blank=True, null=True)),
                ("Date", models.DateField()),
                ("Time", models.TimeField()),
                ("Origin", models.CharField(max_length=50)),
                ("Comments", models.TextField(blank=True, null=True)),
                (
                    "RiskCategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "IncidentCategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "RiskPriority",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("Attachments", models.TextField(blank=True, null=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("Status", models.CharField(blank=True, max_length=45, null=True)),
                ("IdentifiedAt", models.DateTimeField(blank=True, null=True)),
                ("RepeatedNot", models.BooleanField(blank=True, null=True)),
                (
                    "CostOfIncident",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("ReopenedNot", models.BooleanField(blank=True, null=True)),
                (
                    "RejectionSource",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INCIDENT", "Rejected as Incident"),
                            ("RISK", "Rejected from Risk"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "AffectedBusinessUnit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("SystemsAssetsInvolved", models.TextField(blank=True, null=True)),
                (
                    "GeographicLocation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Criticality", models.CharField(blank=True, max_length=20, null=True)),
                ("InitialImpactAssessment", models.TextField(blank=True, null=True)),
                ("InternalContacts", models.TextField(blank=True, null=True)),
                ("ExternalPartiesInvolved", models.TextField(blank=True, null=True)),
                ("RegulatoryBodies", models.TextField(blank=True, null=True)),
                (
                    "RelevantPoliciesProceduresViolated",
                    models.TextField(blank=True, null=True),
                ),
                ("ControlFailures", models.TextField(blank=True, null=True)),
                ("LessonsLearned", models.TextField(blank=True, null=True)),
                (
                    "IncidentClassification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("PossibleDamage", models.TextField(blank=True, null=True)),
                ("AssignerId", models.IntegerField(blank=True, null=True)),
                ("ReviewerId", models.IntegerField(blank=True, null=True)),
                ("MitigationDueDate", models.DateTimeField(blank=True, null=True)),
                ("AssignedDate", models.DateTimeField(blank=True, null=True)),
                ("AssignmentNotes", models.TextField(blank=True, null=True)),
                ("IncidentFormDetails", models.JSONField(blank=True, null=True)),
                (
                    "MitigationCompletedDate",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "AuditId",
                    models.ForeignKey(
                        blank=True,
                        db_column="AuditId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.audit",
                    ),
                ),
                (
                    "ComplianceId",
                    models.ForeignKey(
                        blank=True,
                        db_column="ComplianceId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.compliance",
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        blank=True,
                        db_column="UserId",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.users",
                    ),
                ),
            ],
            options={
                "db_table": "incidents",
            },
        ),
        migrations.CreateModel(
            name="AuditFinding",
            fields=[
                (
                    "AuditFindingsId",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Evidence", models.TextField()),
                (
                    "Check",
                    models.CharField(
                        choices=[
                            ("0", "Not Started"),
                            ("1", "In Progress"),
                            ("2", "Completed"),
                            ("3", "Not Applicable"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "MajorMinor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Minor"),
                            ("1", "Major"),
                            ("2", "Not Applicable"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("HowToVerify", models.TextField(blank=True, null=True)),
                ("Impact", models.TextField(blank=True, null=True)),
                ("Recommendation", models.TextField(blank=True, null=True)),
                ("DetailsOfFinding", models.TextField(blank=True, null=True)),
                ("Comments", models.TextField(blank=True, null=True)),
                ("CheckedDate", models.DateTimeField(blank=True, null=True)),
                ("AssignedDate", models.DateTimeField()),
                (
                    "AuditId",
                    models.ForeignKey(
                        db_column="AuditId",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="grc.audit",
                    ),
                ),
                (
                    "ComplianceId",
                    models.ForeignKey(
                        db_column="ComplianceId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.compliance",
                    ),
                ),
                (
                    "UserId",
                    models.ForeignKey(
                        db_column="UserId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.users",
                    ),
                ),
            ],
            options={
                "db_table": "audit_findings",
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="Assignee",
            field=models.ForeignKey(
                db_column="assignee",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignee",
                to="grc.users",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="Auditor",
            field=models.ForeignKey(
                db_column="auditor",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditor",
                to="grc.users",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="Reviewer",
            field=models.ForeignKey(
                db_column="reviewer",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer",
                to="grc.users",
            ),
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("AssignedAt", models.DateTimeField()),
                (
                    "AssigneeId",
                    models.ForeignKey(
                        db_column="assignee_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_assignee",
                        to="grc.users",
                    ),
                ),
                (
                    "FindingId",
                    models.ForeignKey(
                        db_column="finding_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.auditfinding",
                    ),
                ),
                (
                    "IncidentId",
                    models.ForeignKey(
                        db_column="IncidentId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.incident",
                    ),
                ),
                (
                    "ReviewerId",
                    models.ForeignKey(
                        db_column="reviewer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_reviewer",
                        to="grc.users",
                    ),
                ),
            ],
            options={
                "db_table": "workflow",
            },
        ),
        migrations.CreateModel(
            name="RBAC",
            fields=[
                (
                    "rbac_id",
                    models.AutoField(
                        db_column="RBACId", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(db_column="UserName", max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GRC Administrator", "GRC Administrator"),
                            ("Compliance Manager", "Compliance Manager"),
                            ("Compliance Officer", "Compliance Officer"),
                            ("Compliance Approver", "Compliance Approver"),
                            (
                                "Executive/Senior Management",
                                "Executive/Senior Management",
                            ),
                            ("Policy Manager", "Policy Manager"),
                            ("Policy Approver", "Policy Approver"),
                            ("Audit Manager", "Audit Manager"),
                            ("Internal Auditor", "Internal Auditor"),
                            ("External Auditor", "External Auditor"),
                            ("Audit Reviewer", "Audit Reviewer"),
                            ("Risk Manager", "Risk Manager"),
                            ("Risk Analyst", "Risk Analyst"),
                            ("Risk Reviewer", "Risk Reviewer"),
                            ("Incident Response Manager", "Incident Response Manager"),
                            ("Incident Analyst", "Incident Analyst"),
                            ("Department Manager", "Department Manager"),
                            ("End User", "End User"),
                        ],
                        db_column="Role",
                        max_length=100,
                    ),
                ),
                (
                    "create_compliance",
                    models.BooleanField(db_column="CreateCompliance", default=False),
                ),
                (
                    "edit_compliance",
                    models.BooleanField(db_column="EditCompliance", default=False),
                ),
                (
                    "approve_compliance",
                    models.BooleanField(db_column="ApproveCompliance", default=False),
                ),
                (
                    "view_all_compliance",
                    models.BooleanField(db_column="ViewAllCompliance", default=False),
                ),
                (
                    "compliance_performance_analytics",
                    models.BooleanField(
                        db_column="CompliancePerformanceAnalytics", default=False
                    ),
                ),
                (
                    "create_policy",
                    models.BooleanField(db_column="CreatePolicy", default=False),
                ),
                (
                    "edit_policy",
                    models.BooleanField(db_column="EditPolicy", default=False),
                ),
                (
                    "approve_policy",
                    models.BooleanField(db_column="ApprovePolicy", default=False),
                ),
                (
                    "create_framework",
                    models.BooleanField(db_column="CreateFramework", default=False),
                ),
                (
                    "approve_framework",
                    models.BooleanField(db_column="ApproveFramework", default=False),
                ),
                (
                    "view_all_policy",
                    models.BooleanField(db_column="ViewAllPolicy", default=False),
                ),
                (
                    "policy_performance_analytics",
                    models.BooleanField(
                        db_column="PolicyPerformanceAnalytics", default=False
                    ),
                ),
                (
                    "assign_audit",
                    models.BooleanField(db_column="AssignAudit", default=False),
                ),
                (
                    "conduct_audit",
                    models.BooleanField(db_column="ConductAudit", default=False),
                ),
                (
                    "review_audit",
                    models.BooleanField(db_column="ReviewAudit", default=False),
                ),
                (
                    "view_audit_reports",
                    models.BooleanField(db_column="ViewAuditReports", default=False),
                ),
                (
                    "audit_performance_analytics",
                    models.BooleanField(
                        db_column="AuditPerformanceAnalytics", default=False
                    ),
                ),
                (
                    "create_risk",
                    models.BooleanField(db_column="CreateRisk", default=False),
                ),
                ("edit_risk", models.BooleanField(db_column="EditRisk", default=False)),
                (
                    "approve_risk",
                    models.BooleanField(db_column="ApproveRisk", default=False),
                ),
                (
                    "assign_risk",
                    models.BooleanField(db_column="AssignRisk", default=False),
                ),
                (
                    "evaluate_assigned_risk",
                    models.BooleanField(
                        db_column="EvaluateAssignedRisk", default=False
                    ),
                ),
                (
                    "view_all_risk",
                    models.BooleanField(db_column="ViewAllRisk", default=False),
                ),
                (
                    "risk_performance_analytics",
                    models.BooleanField(
                        db_column="RiskPerformanceAnalytics", default=False
                    ),
                ),
                (
                    "create_incident",
                    models.BooleanField(db_column="CreateIncident", default=False),
                ),
                (
                    "edit_incident",
                    models.BooleanField(db_column="EditIncident", default=False),
                ),
                (
                    "assign_incident",
                    models.BooleanField(db_column="AssignIncident", default=False),
                ),
                (
                    "evaluate_assigned_incident",
                    models.BooleanField(
                        db_column="EvaluateAssignedIncident", default=False
                    ),
                ),
                (
                    "escalate_to_risk",
                    models.BooleanField(db_column="EscalateToRisk", default=False),
                ),
                (
                    "view_all_incident",
                    models.BooleanField(db_column="ViewAllIncident", default=False),
                ),
                (
                    "incident_performance_analytics",
                    models.BooleanField(
                        db_column="IncidentPerformanceAnalytics", default=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_column="UpdatedAt"),
                ),
                (
                    "is_active",
                    models.CharField(
                        choices=[("Y", "Yes"), ("N", "No")],
                        db_column="IsActive",
                        default="Y",
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="UserId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grc.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "RBAC Permission",
                "verbose_name_plural": "RBAC Permissions",
                "db_table": "rbac",
                "ordering": ["username", "role"],
                "unique_together": {("user", "role")},
            },
        ),
        migrations.CreateModel(
            name="ExternalApplicationSyncLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Sync"),
                            ("incremental", "Incremental Sync"),
                            ("manual", "Manual Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("records_synced", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("sync_started_at", models.DateTimeField()),
                ("sync_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="grc.externalapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_sync_logs",
                        to="grc.users",
                    ),
                ),
            ],
            options={
                "db_table": "external-application-sync-logs",
                "ordering": ["-sync_started_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "sync_started_at"],
                        name="external-ap_applica_38ebdf_idx",
                    ),
                    models.Index(
                        fields=["user", "sync_started_at"],
                        name="external-ap_user_id_f92354_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalApplicationConnection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("connection_token", models.TextField(blank=True, null=True)),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "projects_data",
                    models.JSONField(
                        blank=True,
                        help_text="Stores all retrieved project data in JSON format",
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="grc.externalapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_connections",
                        to="grc.users",
                    ),
                ),
            ],
            options={
                "db_table": "external-applications-connections",
                "indexes": [
                    models.Index(
                        fields=["user", "application"],
                        name="external-ap_user_id_be5e98_idx",
                    ),
                    models.Index(
                        fields=["connection_status"],
                        name="external-ap_connect_dfc8d9_idx",
                    ),
                ],
                "unique_together": {("application", "user")},
            },
        ),
    ]
