name: Build, Push, Pull, and Run Docker Image to/from ECR

on:
  push:
    branches:
      - main
      - master

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 480940871468.dkr.ecr.ap-south-1.amazonaws.com
  BACKEND_IMAGE: 480940871468.dkr.ecr.ap-south-1.amazonaws.com/grc_tprm_backend:latest
  DOCKERFILE_PATH: ./grc_backend/Dockerfile  # Ensure this path is correct if the Dockerfile is inside a folder.

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        run: |
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

      - name: Build Backend Docker image
        working-directory: grc_backend  # Path to the backend directory where Dockerfile is
        run: |
          docker build -t grc_tprm_backend:latest -f ${{ env.DOCKERFILE_PATH }} .

      - name: Tag Backend image for ECR
        run: |
          docker tag grc_tprm_backend:latest "${BACKEND_IMAGE}"

      - name: Push Backend to ECR
        run: |
          docker push "${BACKEND_IMAGE}"
          echo "Backend image pushed to ECR successfully"

  pull-and-run:
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Configure AWS credentials
        run: |
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}

      - name: Pull Docker image from ECR
        run: |
          docker pull "${BACKEND_IMAGE}"
          echo "Docker image pulled from ECR successfully"

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 "${BACKEND_IMAGE}"  # Expose the container port (adjust as needed)
          echo "Docker container is running."
